In [6]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


In [8]:
data = np.random.randint(0,100,(10,2))

In [9]:
data

array([[42, 17],
       [47,  5],
       [73, 26],
       [56, 69],
       [ 3, 53],
       [85, 51],
       [20, 81],
       [62, 21],
       [88, 45],
       [72, 54]])

In [10]:
scaler_model = MinMaxScaler()

In [11]:
type (scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [12]:
scaler_model.fit(data)

c:\users\bikramaditya.padhi\pycharmprojects\venv\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [13]:
scaler_model.transform(data)

array([[0.45882353, 0.15789474],
       [0.51764706, 0.        ],
       [0.82352941, 0.27631579],
       [0.62352941, 0.84210526],
       [0.        , 0.63157895],
       [0.96470588, 0.60526316],
       [0.2       , 1.        ],
       [0.69411765, 0.21052632],
       [1.        , 0.52631579],
       [0.81176471, 0.64473684]])

In [14]:
scaler_model.fit_transform(data)

c:\users\bikramaditya.padhi\pycharmprojects\venv\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.45882353, 0.15789474],
       [0.51764706, 0.        ],
       [0.82352941, 0.27631579],
       [0.62352941, 0.84210526],
       [0.        , 0.63157895],
       [0.96470588, 0.60526316],
       [0.2       , 1.        ],
       [0.69411765, 0.21052632],
       [1.        , 0.52631579],
       [0.81176471, 0.64473684]])

In [15]:
import pandas as pd

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [16]:
myData = np.random.randint(0,101,(50,4))

In [24]:
df = pd.DataFrame(data=myData, columns=['F1','F2','F3','Label'])

In [25]:
df

F1  F2  F3  Label
0   52  68  18     41
1   50   2  19     65
2   87  52  31     86
3   27  82   1     73
4   75  72   2     36
5   53  21  22     45
6    4  19   5      7
7   36  38  53     27
8   76  63  82     67
9   72  71  89     68
10  81  39   0     87
11  24  41   5      1
12  24  38  33     75
13  51  16  40      0
14  38  11  24     76
15  96  91  81     52
16  48  42  23     48
17   1  73  38     78
18  37  37   8     69
19   9  18  92     67
20  50  10   0     55
21  64  81  21      9
22  69  16  31     65
23  18   1  73     36
24  36   2  25     55
25   6  11  86     57
26  86  86  27     19
27  95  42  92     52
28  78  53  81     80
29   7  28   2     17
30   4  17  48     30
31  16  24  97     27
32  73   6  71     10
33  47  44  92      2
34  77   2  49      8
35  48  63  16     92
36  43  39  43     27
37  88  45  29     69
38  14  79  52    100
39  56  58  20     31
40  24  43  49     28
41  85  43   7     97
42  81  72  21     69
43  45  16  56     83
44  11  18   1     47
45  81   2  24     64
46  63  21   0     55
47  42  63  95     29
48  31  63  36     70
49  18  64   0      2

In [26]:
x = df[['F1','F2','F3']]

In [27]:
x

F1  F2  F3
0   52  68  18
1   50   2  19
2   87  52  31
3   27  82   1
4   75  72   2
5   53  21  22
6    4  19   5
7   36  38  53
8   76  63  82
9   72  71  89
10  81  39   0
11  24  41   5
12  24  38  33
13  51  16  40
14  38  11  24
15  96  91  81
16  48  42  23
17   1  73  38
18  37  37   8
19   9  18  92
20  50  10   0
21  64  81  21
22  69  16  31
23  18   1  73
24  36   2  25
25   6  11  86
26  86  86  27
27  95  42  92
28  78  53  81
29   7  28   2
30   4  17  48
31  16  24  97
32  73   6  71
33  47  44  92
34  77   2  49
35  48  63  16
36  43  39  43
37  88  45  29
38  14  79  52
39  56  58  20
40  24  43  49
41  85  43   7
42  81  72  21
43  45  16  56
44  11  18   1
45  81   2  24
46  63  21   0
47  42  63  95
48  31  63  36
49  18  64   0

In [28]:
y = df['Label']

In [29]:
y

0      41
1      65
2      86
3      73
4      36
5      45
6       7
7      27
8      67
9      68
10     87
11      1
12     75
13      0
14     76
15     52
16     48
17     78
18     69
19     67
20     55
21      9
22     65
23     36
24     55
25     57
26     19
27     52
28     80
29     17
30     30
31     27
32     10
33      2
34      8
35     92
36     27
37     69
38    100
39     31
40     28
41     97
42     69
43     83
44     47
45     64
46     55
47     29
48     70
49      2
Name: Label, dtype: int32

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
train_test_split

<function sklearn.model_selection._split.train_test_split(*arrays, **options)>

In [35]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [36]:
X_train.shape

(35, 3)